# Generated by Django 5.0.6 on 2024-07-22 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciclo', models.CharField(max_length=50, verbose_name='Nombre del Ciclo')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
            },
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=50, verbose_name='Código')),
                ('nombre_malla', models.CharField(max_length=80, verbose_name='Nombre de la Malla')),
                ('tituloOtorgado', models.CharField(max_length=100, verbose_name='Título Otorgado')),
            ],
            options={
                'verbose_name': 'Malla Curricular',
                'verbose_name_plural': 'Mallas Curriculares',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_periodo', models.CharField(default='', max_length=50, verbose_name='Código de Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_asignatura', models.CharField(max_length=50, unique=True, verbose_name='Código de Asignatura')),
                ('nombre_asignatura', models.CharField(max_length=100, verbose_name='Nombre de Asignatura')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prediccion.ciclo', verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.AddField(
            model_name='ciclo',
            name='malla_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prediccion.mallacurricular', verbose_name='Malla Curricular'),
        ),
        migrations.CreateModel(
            name='Historico_Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculados', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Matriculados')),
                ('reprobados', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reprobados')),
                ('abandonaron', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Abandonaron')),
                ('aprobados', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aprobados')),
                ('aplazadores', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aplazadores')),
                ('desertores', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desertores')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prediccion.periodoacademico', verbose_name='Periodo Académico')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculados', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Matriculados')),
                ('reprobados', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reprobados')),
                ('abandonaron', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Abandonaron')),
                ('aprobados', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aprobados')),
                ('aplazadores', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aplazadores')),
                ('desertores', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desertores')),
                ('ciclo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Prediccion.ciclo', verbose_name='Ciclo')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prediccion.periodoacademico', verbose_name='Periodo Académico')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
            },
        ),
    ]
