# Generated by Django 5.0.6 on 2024-07-08 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='cantidad_asignaturas',
        ),
    ]
