# Generated by Django 5.0.6 on 2024-07-25 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_periodo',
            name='abandonaron',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Abandonaron'),
        ),
        migrations.AlterField(
            model_name='historico_periodo',
            name='aplazadores',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aplazadores'),
        ),
        migrations.AlterField(
            model_name='historico_periodo',
            name='aprobados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aprobados'),
        ),
        migrations.AlterField(
            model_name='historico_periodo',
            name='matriculados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Matriculados'),
        ),
        migrations.AlterField(
            model_name='historico_periodo',
            name='reprobados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reprobados'),
        ),
    ]
