# Generated by Django 5.0.6 on 2024-07-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0003_alter_historico_periodo_abandonaron_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico_periodo',
            options={'verbose_name': 'Histórico de Periodo', 'verbose_name_plural': 'Históricos de Periodos'},
        ),
    ]
