# Generated by Django 5.0.6 on 2024-07-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0003_alter_asignatura_codigo_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codigo_asignatura',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Asignatura'),
        ),
    ]
