# Generated by Django 5.0.6 on 2024-07-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0004_alter_historico_periodo_options_delete_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='aplazadores',
        ),
        migrations.RemoveField(
            model_name='historico_periodo',
            name='aplazadores',
        ),
    ]
