# Generated by Django 5.0.6 on 2024-07-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0004_alter_asignatura_codigo_asignatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='desertores',
            new_name='abandonaron',
        ),
    ]
