# Generated by Django 5.0.6 on 2024-07-18 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0005_rename_desertores_historico_abandonaron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='abandonaron',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='abandonaron'),
        ),
    ]
