# Generated by Django 5.0.6 on 2024-07-18 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0006_alter_historico_abandonaron'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoacademico',
            options={'verbose_name': 'Periodo Académico', 'verbose_name_plural': 'Desertores'},
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='desertores',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desertores'),
        ),
    ]
